#!/bin/bash

mkdir corpus_to_align
mkdir corpus_to_align/source_language_corpus_untokenized
mkdir corpus_to_align/target_language_corpus_untokenized
mkdir corpus_to_align/source_language_corpus_tokenized
mkdir corpus_to_align/target_language_corpus_tokenized
